/**:
  ros__parameters:
    dataset_root_dir: /data/dataset
    lidar_topic: /sensing/lidar/concatenated/pointcloud
    camera_topic: /sensing/camera/camera_top/image_raw
    save_interval: 0.5
    timeout_threshold: 1.5
    id_heartbeat_timeout: 1.5
