/**:
  ros__parameters:
    dataset_root_dir: /data/datasets
    lidar_topic: /sensing/lidar/top/pointcloud_raw_ex
    camera_topic: /sensing/camera/camera_top/image_raw
    save_interval: 0.5
    sync_slop: 0.1
    timeout_threshold: 1.5
    id_heartbeat_timeout: 1.5
